name: Deploy Storybook to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "packages/components/**"

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    # Job steps
    steps:
      # Manual Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Node
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Set up pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.7
          run_install: false

      - name: Deploy github pages
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: pnpm install # default: npm ci
          build_command: npx turbo run build-storybook # default: npm run build-storybook
          path: packages/components/storybook-static # default: dist/storybook
          checkout: false # default: true
