name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Deploy-Preview:
    if: ${{ ! startsWith(github.event.pull_request.title, 'auto-changesets-release') }}
    runs-on: ubuntu-latest
    steps:
      # Manual Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Node
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Set up pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.7
          run_install: false

      - name: Install Vercel CLI
        run: pnpm i -g vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
